# name: Update streak stats

# on:
#   schedule:
#     # سيحدث البيانات تلقائيًا كل 6 ساعات (تستطيع تغيير الوقت)
#     - cron: '0 */2 * * *'
#   workflow_dispatch: # يسمح لك بتشغيله يدويًا

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - uses: actions/checkout@v3
#       - uses: DenverCoder1/github-readme-streak-stats@main
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # استبدل minanasser باسم المستخدم الخاص بك
#           user: minanasser
#           # يمكنك تغيير المظهر إذا أردت، الإعدادات الحالية:
#           theme: radical
#           background: 000000
#           border: 8B5CF6
#           dates: 8B5CF6
#           fire: 8B5CF6
